name: training_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  go_router: ^14.1.4
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.3.5
  flutter_svg: ^2.0.10+1

flutter_gen:
  output: lib/presentation/gen/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/svgs/figure_logo.svg
    - assets/images/svgs/figure_logo2.svg

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Medium.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
